version: 2

updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10

updates:
- package-ecosystem: npm
  directory: "/application"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
