[package]
name = "weresocool"
version = "0.6.0"
edition = "2018"
authors = ["Danny Meyer <weresocool@xasopheno.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "GPL-3.0" 
autobins = false
repository = "https://github.com/xasopheno/WereSoCool"
keywords = ["microtonal", "binaural", "composition",  "audio", "music"]
categories = ["multimedia::audio"]
readme = "README.md"

[dependencies]
weresocool_parser = { path = "parser" }
weresocool_ast = { path = "ast" }
weresocool_error = { path = "error" } 
portaudio = "0.7.0"
rand = "0.7.3"
hound = "3.4.0"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
serde_derive = "1.0.104"
colored = "1.9.3"
pbr = "1.0.3"
clap = "2.33.1"
num-rational = "0.2.4"
rayon = "1.3.0"
indexmap = { version = "1.4.0", features = ["serde-1"] }
difference = "2.0.0"
term = "0.6.1"
uuid = { version = "0.8.1", features = ["v4"] }
num-complex = "0.2.4"
num = "0.2.1"
csv = "1.1.3"
failure = "0.1.8"
failure_derive = "0.1.8"
futures = "0.3.5"
bytes = "0.5.4"
env_logger = "0.7.1"
test-generator = "0.3.0"
float-cmp = "0.8.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3"
#listenfd = "0.3.3"

[[bench]]
name = "render_batch_bench"
harness = false
[[bench]]
name = "nf_to_vec_renderable_bench"
harness = false

[workspace]
members = [
    "ast",
    "parser",
    "error",
]

[[bin]]
name = "wsc"
path = "bin/wsc.rs"

[[bin]]
name = "print"
path = "bin/print.rs"

[[bin]]
name = "stems"
path = "bin/stems.rs"

[[bin]]
name = "real_time"
path = "bin/real_time.rs"

[[bin]]
name = "mic"
path = "bin/real_time_mic.rs"

[[bin]]
name = "scratch"
path = "bin/pad.rs"

[[bin]]
name = "snapshot"
path = "bin/snapshot.rs"

