[package]
name = "weresocool"
version = "0.6.0"
edition = "2018"
authors = ["Danny <weresocool@xasopheno.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "GPL-3.0" 
autobins = false
repository = "https://github.com/xasopheno/WereSoCool"
keywords = ["microtonal", "binaural", "composition",  "audio", "music"]
categories = ["multimedia::audio"]
readme = "README.md"


[dependencies]
weresocool_analyze = { path = "analyze" }
weresocool_parser = { path = "parser" }
weresocool_ast = { path = "ast" }
weresocool_error = { path = "error" } 
weresocool_lame = { path = "lame" } 
weresocool_shared = { path = "shared" } 
weresocool_instrument = { path = "instrument" } 
portaudio = "0.7.0"
rand = "0.8.2"
hound = "3.4.0"
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"
serde_derive = "1.0.119"
colored = "2.0.0"
pbr = "1.0.4"
clap = "2.33.3"
num-rational = "0.3.2"
rayon = "1.5.0"
indexmap = { version = "1.6.1", features = ["serde-1"] }
difference = "2.0.0"
term = "0.7.0"
uuid = { version = "0.8.2", features = ["v4"] }
num-complex = "0.3.1"
num = "0.3.1"
csv = "1.1.5"
failure = "0.1.8"
failure_derive = "0.1.8"
futures = "0.3.12"
bytes = "1.0.1"
env_logger = "0.8.2"
test-generator = "0.3.0"
float-cmp = "0.8.0"
pretty_assertions = "0.6.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3.3"

[[bench]]
name = "render_batch_bench"
harness = false
[[bench]]
name = "nf_to_vec_renderable_bench"
harness = false

[workspace]
members = [
    "analyze",
    "ast",
    "error",
    "instrument",
    "lame",
    "parser",
    "shared",
    # "portaudio",
    # "portaudio/rust-portaudio-sys",
    "application/server",
]

[[bin]]
name = "wsc"
path = "bin/wsc.rs"

[[bin]]
name = "stems"
path = "bin/stems.rs"

[[bin]]
name = "real_time"
path = "bin/real_time.rs"

[[bin]]
name = "mic"
path = "bin/real_time_mic.rs"

[[bin]]
name = "scratch"
path = "bin/pad.rs"

[[bin]]
name = "snapshot"
path = "bin/snapshot.rs"

