[package]
name = "weresocool"
version = "2.0.0"
edition = "2021"
authors = ["Danny <weresocool@xasopheno.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "GPL-3.0" 
autobins = false
repository = "https://github.com/xasopheno/WereSoCool"
keywords = ["microtonal", "binaural", "composition",  "audio", "music"]
categories = ["multimedia::audio"]
readme = "README.md"
resolver="2"
default-run = "weresocool"

exclude = [
    "imgs/*",
]

[package.metadata.arch]
arch = ["x86_64"]
makedepends = ["cargo", "lame", "vorbis-tools"]
depends = ["lame", "vorbis-tools"]
provides = ["weresocool"]

[target.'cfg(all(target_os = "windows", not(target_arch = "wasm32")))'.dependencies]
weresocool_core = { path="core", version = "^2.0.0", features = ["windows"] }
weresocool_error = { path = "error", version = "^2.0.0", features=["windows"] }
[target.'cfg(all(target_os = "linux", not(target_arch = "wasm32")))'.dependencies]
weresocool_core = { path="core", version = "^2.0.0", features = ["windows"] }
weresocool_error = { path = "error", version = "^2.0.0", features=["windows"] }
[target.'cfg(all(target_os = "macos", not(target_arch = "wasm32")))'.dependencies]
weresocool_core = { path="core", version = "^2.0.0", features = ["app"] }
weresocool_error = { path = "error", version = "^2.0.0", features=["app"] }

[dependencies]
weresocool_core = { path="core", version = "^2.0.0", default-features=false }
weresocool_error = { path = "error", version = "^2.0.0", default-features=false } 
weresocool_parser = { path = "parser", version = "^2.0.0", default-features=false, optional=true }
weresocool_ast = { path = "ast", version = "^2.0.0", default-features=false, optional=true }
weresocool_instrument = { path = "instrument", version = "^2.0.0", default-features=false, optional=true } 
weresocool_portaudio = { version = "1.0.47", optional = true, git = "https://github.com/xasopheno/weresocool_portaudio"}
scop = { path = "scop", version = "^2.0.0" }
opmap = { path = "opmap", version = "^2.0.0" }
weresocool_shared = { path = "shared", version = "^2.0.0" } 
weresocool_analyze = { path = "analyze", version = "^2.0.0" }
weresocool_ring_buffer = { path = "ring_buffer", version = "^2.0.0" }
weresocool_formatter = { path = "formatter", version = "^2.0.0", default-features=false, optional=true }
clap = "4.5"
thiserror = "2.0"
notify = "6.1"
zip = { version="2.2", optional=true }
hound = { version="3.5", optional=true }
assert_cmd = { version="2.0", optional=true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
term = "1.0"
num-rational = "0.4"
indexmap = { version = "2.6", features = ["serde"] }
difference = "2.0"
test-generator = "0.3"
crossbeam-channel = "0.5"
indoc = "2.0"
colored = "2.1"
rand = { version="0.8", features=["std"]}
log = "0.4"

[dev-dependencies]
pretty_assertions = "1.4"
criterion = "0.5"
temp-dir = "0.1"

[features]
default=["app"]
app=[
    "weresocool_error/app",
    "weresocool_core/app",
    "weresocool_parser/app",
    "weresocool_instrument/app",
    "weresocool_ast/app",
    "weresocool_core/app",
    "weresocool_formatter/app",
    "weresocool_portaudio",
    "zip",
    "hound",
    "assert_cmd",
]
windows=[
    "weresocool_error/windows", 
    "weresocool_core/windows",
    "weresocool_parser/app", 
    "weresocool_instrument/app", 
    "weresocool_ast/app",
    "weresocool_portaudio",
    "zip",
    "hound",
    "assert_cmd",
]
wasm = [
    "weresocool_core/wasm",
    "weresocool_ast/wasm", 
    "weresocool_instrument/wasm", 
    "weresocool_parser/wasm", 
    "weresocool_error/wasm", 
]


[[bench]]
name = "render_batch_bench"
harness = false
[[bench]]
name = "nf_to_vec_renderable_bench"
harness = false

[workspace]
members = [
    "core",
    "analyze",
    "filter",
    "opmap",
    "ast",
    "error",
    "formatter",
    "instrument",
    "lame",
    "parser",
    "shared",
    "scop",
    "ring_buffer",
    "vorbis",
    "weresocool_synth",
    "weresocool_events",
]


[[bin]]
name = "weresocool"
path = "src/main.rs"

# [[bin]]
# name = "stems"
# path = "bin/stems.rs"

# [[bin]]
# name = "real_time"
# path = "bin/real_time.rs"

# [[bin]]
# name = "mic"
# path = "bin/real_time_mic.rs"

# [[bin]]
# name = "scratch"
# path = "bin/pad.rs"

## This is a hack. I don't want this binary to be built for users,
## but I need it to run tests.
[[example]]
name = "snapshot"
path = "bin/snapshot.rs"

