[package]
name = "weresocool"
version = "0.3.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "MIT"
autobins = false

[dependencies]
portaudio = "0.7.0"
rand = "0.5.1"
hound = "3.4.0"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.27"
colored = "1.6"
pbr = "1.0.1"
socool_parser = { path = "parser" }
clap = "2.32.0"
num-rational = "0.2"
rayon = "1.0"

[[bin]]
name = "wsc"
path = "bin/wsc.rs"

[[bin]]
name = "mic"
path = "bin/mic.rs"

[[bin]]
name = "scratch"
path = "bin/pad.rs"
