[package]
name = "weresocool"
version = "0.5.0"
edition = "2018"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "MIT"
autobins = false

[dependencies]
portaudio = "0.7.0"
rand = "0.7.0"
hound = "3.4.0"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
colored = "1.7.0"
pbr = "1.0.1"
socool_parser = { path = "parser" }
socool_ast = { path = "ast" }
clap = "2.32.0"
num-rational = "0.2"
rayon = "1.1"
indexmap = { version = "1", features = ["serde-1"] }
difference = "2.0.0"
term = "0.6.0"
uuid = { version = "0.7.2", features = ["v4"] }
num-complex = "0.2.3"
num = "0.2.0"
csv = "1.1.1"

[[bin]]
name = "wsc"
path = "bin/wsc.rs"

[[bin]]
name = "mic"
path = "bin/mic.rs"

[[bin]]
name = "scratch"
path = "bin/pad.rs"

[[bin]]
name = "snapshot"
path = "bin/snapshot.rs"
