[package]
name = "weresocool"
version = "0.5.0"
edition = "2018"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "GPL-3.0" 
autobins = false

[dependencies]
portaudio = "0.7.0"
rand = "0.7.2"
hound = "3.4.0"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.44"
colored = "1.9.1"
pbr = "1.0.2"
socool_parser = { path = "parser" }
socool_ast = { path = "ast" }
error = { path = "error" } 
clap = "2.33.0"
num-rational = "0.2.2"
rayon = "1.3.0"
indexmap = { version = "1.3.0", features = ["serde-1"] }
difference = "2.0.0"
term = "0.6.1"
uuid = { version = "0.8.1", features = ["v4"] }
num-complex = "0.2.3"
num = "0.2.0"
csv = "1.1.1"
watch = "0.1.0"
failure = "0.1.6"
failure_derive = "0.1.6"
termion = "1.5.4"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3"

[[bench]]
name = "render_batch_bench"
harness = false
[[bench]]
name = "nf_to_vec_renderable_bench"
harness = false

[workspace]
members = [
    "ast",
    "parser",
    "error",
]

[[bin]]
name = "wsc"
path = "bin/wsc.rs"

[[bin]]
name = "stems"
path = "bin/stems.rs"

[[bin]]
name = "real_time"
path = "bin/real_time.rs"

[[bin]]
name = "scratch"
path = "bin/pad.rs"

[[bin]]
name = "snapshot"
path = "bin/snapshot.rs"

