[package]
name = "weresocool"
version = "0.4.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "MIT"
autobins = false

[dependencies]
portaudio = "0.7.0"
rand = "0.5.1"
hound = "3.4.0"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.36"
colored = "1.6"
pbr = "1.0.1"
socool_parser = { path = "parser" }
socool_ast = { path = "socool_ast" }
clap = "2.32.0"
num-rational = "0.2"
rayon = "1.0"
indexmap = { version = "1", features = ["serde-1"] }
difference = "2.0.0"
term = "0.5.1"

[[bin]]
name = "wsc"
path = "bin/wsc.rs"

[[bin]]
name = "mic"
path = "bin/mic.rs"

[[bin]]
name = "scratch"
path = "bin/pad.rs"

[[bin]]
name = "snapshot"
path = "bin/snapshot.rs"
