[package]
name = "weresocool"
version = "0.6.0"
edition = "2018"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "GPL-3.0" 
autobins = false
repository = "https://github.com/xasopheno/WereSoCool"
keywords = ["microtonal", "binaural", "composition", "audio", "synth", "music"]
categories = ["multimedia::audio"]
readme = "README.md"

[dependencies]
socool_parser = { path = "parser" }
socool_ast = { path = "ast" }
error = { path = "error" } 

portaudio = "0.7.0"
rand = "0.7.3"
hound = "3.4.0"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.46"
colored = "1.9.2"
pbr = "1.0.2"
clap = "2.33.0"
num-rational = "0.2.3"
rayon = "1.3.0"
indexmap = { version = "1.3.1", features = ["serde-1"] }
difference = "2.0.0"
term = "0.6.1"
uuid = { version = "0.8.1", features = ["v4"] }
num-complex = "0.2.4"
num = "0.2.1"
csv = "1.1.3"
watch = "0.1.0"
failure = "0.1.6"
failure_derive = "0.1.6"

[dev-dependencies]
pretty_assertions = "0.6.1"
criterion = "0.3"

[[bench]]
name = "render_batch_bench"
harness = false
[[bench]]
name = "nf_to_vec_renderable_bench"
harness = false

[workspace]
members = [
    "ast",
    "parser",
    "error",
]

[[bin]]
name = "wsc"
path = "bin/wsc.rs"

[[bin]]
name = "stems"
path = "bin/stems.rs"

[[bin]]
name = "real_time"
path = "bin/real_time.rs"

[[bin]]
name = "scratch"
path = "bin/pad.rs"

[[bin]]
name = "snapshot"
path = "bin/snapshot.rs"

