[package]
name = "weresocool_ast"
version = "0.5.0"
authors = ["Danny Meyer <weresocool@xasopheno.com>"]
edition = "2018"
description = "AST for WereSoCool"
license = "GPL-3.0" 

[dependencies]
weresocool_error = { path = "../error" }
weresocool_shared = { path = "../shared" }
num-rational = {version = "0.3", features = ["serde"]} 
rand = "0.7.3"
serde = { version = "1.0.116", features = ["derive"] }
pretty_assertions = "0.6.1"
indexmap = "1.4.0"
colored = "1.9.3"
num-traits = "0.2.14"
num-integer = "0.1.44"
polynomials = "0.2.4"
