[package]
name = "weresocool_ast"
version = "0.5.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"
description = "AST for WereSoCool"
license = "GPL-3.0" 

[dependencies]
num-rational = "0.2"
rand = "0.7.3"
serde = { version = "1.0.103", features = ["derive"] }
pretty_assertions = "0.6.1"
indexmap = "1.3.1"
colored = "1.9.3"
