[package]
name = "socool_ast"
version = "0.5.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"

[dependencies]
num-rational = "0.2"
rand = "0.7.1"
serde = { version = "1.0.100", features = ["derive"] }
pretty_assertions = "0.6.1"
indexmap = "1.2.0"
colored = "1.8.0"
