[package]
name = "weresocool_parser"
version = "0.5.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing
description = "Parser for WereSoCool"
license = "GPL-3.0" 

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
lalrpop-util = "0.18.1"
regex = "1"
colored = "1.9"
num-rational = "0.2"
indexmap = "1.3.1"
weresocool_ast = { path = "../ast" }
weresocool_error = { path = "../error" }
