[package]
name = "weresocool_parser"
version = "2.0.0"
authors = ["Danny Meyer <weresocool@xasopheno.com>"]
edition = "2021"
build = "build.rs" # LALRPOP preprocessing
description = "Parser for WereSoCool"
license = "GPL-3.0" 
resolver="2"

[build-dependencies.lalrpop]
version = "0.22.2"
features = ["lexer"]

[dependencies]
weresocool_ast = { path = "../ast", version = "^2.0.0", default-features=false, optional=true }
weresocool_error = { path = "../error", version = "^2.0.0", default-features=false, optional=true }
weresocool_shared = { path = "../shared", version = "^2.0.0" }
scop = { path = "../scop", version = "^2.0.0" }
lalrpop-util = { version="0.22.2", features=["lexer"]}
regex = "1.11"
colored = "2.1"
num-rational = "0.4"
indexmap = "2.6"
rand = { version="0.8", features=["std"]}
path-clean = "1.0"
uuid = { version = "1.11", features = ["serde", "v4"] }
num-traits = "0.2"

[features]
default=["app"]
app=["weresocool_error/app", "weresocool_ast/app"]
wasm=["weresocool_error/wasm", "weresocool_ast/wasm"]
