[package]
name = "socool_parser"
version = "0.5.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"
build = "build.rs" # LALRPOP preprocessing

[build-dependencies]
lalrpop = "0.17.1"

[dependencies]
lalrpop-util = "0.17.2"
regex = "1"
colored = "1.9"
num-rational = "0.2"
socool_ast = { path = "../ast" }
indexmap = "1.3.2"
error = { path = "../error" }
