[package]
name = "weresocool_instrument"
version = "0.1.0"
authors = ["xasopheno <danny@xasopheno.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
weresocool_ast = { path = "../ast" }
weresocool_error = { path = "../error" }
weresocool_parser = { path = "../parser" }
weresocool_shared = { path = "../shared" }
serde = { version = "1.0.116", features = ["derive"] }
lanceverb = { path = "lanceverb" }
rayon = "1.3.0"
num-rational = "0.3.0"
rand = "0.7.3"
dsp-chain = { optional = true, version = "0.13.1" }
# dasp = "0.11.0"
[features]
default = ["dsp-chain"]
