[package]
name = "error"
version = "0.1.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"

[dependencies]
portaudio = "0.7.0"
hound = "3.4.0"
serde_json = "1.0.40"
csv = "1.1.1"
failure = "0.1.6"
failure_derive = "0.1.5"
