[package]
name = "weresocool_error"
version = "0.1.0"
authors = ["Danny Meyer <weresocool@xasopheno.com>"]
edition = "2018"
description = "Errors for WereSoCool"
license = "GPL-3.0"

[dependencies]
weresocool_lame = { path = "../lame", optional=true}
portaudio = {version="0.7.0", optional=true}
hound = "3.4.0"
serde_json = "1.0.61"
csv = "1.1.5"
failure = "0.1.8"
failure_derive = "0.1.8"
serde = { version = "1.0.119", features = ["derive"] }
wasm-bindgen = { version="0.2.71", optional=true, features=["serde-serialize"] }
thiserror = "1.0.24"

[features]
default= ["app"]
app = ["portaudio", "weresocool_lame"]
wasm = ["wasm-bindgen"]

