[package]
name = "weresocool_error"
version = "0.1.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"
description = "Errors for WereSoCool"
license = "GPL-3.0"

[dependencies]
portaudio = "0.7.0"
hound = "3.4.0"
serde_json = "1.0.51"
csv = "1.1.3"
failure = "0.1.7"
failure_derive = "0.1.7"
serde = { version = "1.0.105", features = ["derive"] }
