[package]
name = "weresocool_error"
version = "2.0.0"
authors = ["Danny Meyer <weresocool@xasopheno.com>"]
edition = "2021"
description = "Errors for WereSoCool"
license = "GPL-3.0"

[target.'cfg(target_os = "macos")'.dependencies]
weresocool_lame = { path = "../lame", version = "^2.0.0" } 

[target.'cfg(target_os = "linux")'.dependencies]
weresocool_lame = { path = "../lame", version = "^2.0.0" } 

[dependencies]
scop = { path = "../scop", version = "^2.0.0" }
weresocool_portaudio = { version = "1.0.47", optional = true, git = "https://github.com/xasopheno/weresocool_portaudio"}
hound = "3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
wasm-bindgen = { version="0.2", optional=true, features=["serde-serialize"] }
thiserror = "2.0"

[features]
default= ["app"]
app = ["weresocool_portaudio"]
windows = ["weresocool_portaudio"]
wasm = ["wasm-bindgen"]

