[package]
name = "weresocool_error"
version = "0.1.0"
authors = ["Danny Meyer <weresocool@xasopheno.com>"]
edition = "2018"
description = "Errors for WereSoCool"
license = "GPL-3.0"

[dependencies]
weresocool_lame = { path = "../lame" }
portaudio = { path = "../portaudio" } 
# portaudio = "0.7.0"
hound = "3.4.0"
serde_json = "1.0.53"
csv = "1.1.3"
failure = "0.1.8"
failure_derive = "0.1.8"
serde = { version = "1.0.111", features = ["derive"] }
