[package]
name = "weresocool_vorbis"
version = "2.0.0"
edition = "2024"
description = "Vorbis for WereSoCool"
license = "GPL-3.0" 
resolver="2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
itertools = "0.10.3"
vorbis-encoder = "0.1.4"
weresocool_error = { path = "../error", version = "^2.0.0", default-features=false }
weresocool_shared = { path = "../shared", version = "^2.0.0" }

[dev-dependencies]
hamcrest2 = "0.3.0"
