[package]
name = "socool_ast"
version = "0.1.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"

[dependencies]
num-rational = "0.2"
rand = "0.5.1"
serde_derive = "1.0.85"
serde = "1.0.85"
serde_json = "1.0.36"
pretty_assertions = "0.5.1"
indexmap = "1.0.2"
