name: Application Tests

on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: yarn install
        working-directory: ./application
        run: |
          yarn install
      - name: yarn ts
        working-directory: ./application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn ts
      - name: yarn lint
        working-directory: ./application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn lint
      - name: yarn build
        working-directory: ./application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: yarn build

      - name: install dependancies
        run: brew install portaudio pkg-config lame

      - name: yarn package
        working-directory: ./application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn package

      - name: test static build 
        working-directory: ./application
        run: ./test/test_static_linking.sh

      - name: yarn test
        working-directory: ./application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn test 

