name: Cool Tests

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependancies
      run: brew install portaudio pkg-config lame

    - name: Build
      run: cargo build --verbose
    - name: Add rustfmt
      run: rustup component add rustfmt
    - name: add clippy
      run: rustup component add clippy
    - name: format
      run: make format_ci 
    - name: clippy 
      run: cargo clippy --all-targets -- -D warnings
    - name: run tests
      run: make test
      
      
